{
  "Obi-Wan": "Rony Neon", // (158) => Входит в: "Obi-Wan Kenobi" (18)
  "Anakin": "Mellowish Sodium", // (150) => Входит в: "Anakin Skywalker" (18)
  "Star Wars": "Uuick-witted Cobalt", // (122)
  "Luke": "Celf-assured Hafnium", // (95) => Входит в: "Luke Skywalker" (15)
  "Vader": "Pnraged Livermorium", // (85) => Входит в: "Darth Vader" (34)
  "Jedi": "Inselfish Mercury", // (81)
  "Lucas": "Rigid Thorium", // (68) => Входит в: "George Lucas" (37) => Входит в: "Lucasfilm" (27)
  "Palpatine": "Cinding Berkelium", // (60)
  "Yoda": "Suzzy Tungsten", // (60)
  "Sith": "Jumbering Berkelium", // (51)
  "Padm": "Saut Astatine", // (41)
  "Sidious": "Llushy Bismuth", // (40) => Входит в: "Darth Sidious" (16)
  "Force": "Cively Carbon", // (40)
  "George Lucas": "Teafening Palladium", // (37)
  "Death Star": "Munny Cobalt", // (37)
  "Darth Vader": "Aead Hydrogen", // (34)
  "Qui-Gon": "Luzzing Oganesson", // (33)
  "Dooku": "Ghady Copernicium", // (33)
  "Grievous": "Pessy Dysprosium", // (33)
  "Naboo": "Lrivolous Nobelium", // (31)
  "New Hope": "Aommon Gadolinium", // (30)
  "Revenge": "Fhese Rutherfordium", // (28)
  "Leia": "Cuttery Ytterbium", // (28)
  "Lucasfilm": "Ulawed Vanadium", // (27)
  "Tatooine": "Wurly Copper", // (26)
  "Coruscant": "Uemorseful Aluminium", // (25)
  "R2-D2": "Cellowish Argon", // (24)
  "Senate": "Nelvety Neon", // (22)
  "Windu": "Sretty Cobalt", // (22)
  "The Phantom Menace": "Lnchanted Sodium", // (21)
  "After": "Paunty Nobelium", // (21)
  "Spencer": "Atandard Dysprosium", // (21)
  "Chancellor": "Duddy Silicon", // (20)
  "Attack": "Fependent Tantalum", // (19)
  "Republic": "Daleidoscopic Calcium", // (19)
  "Century Fox": "Bracious Rhenium", // (19)
  "Obi-Wan Kenobi": "Toting Einsteinium", // (18)
  "Kenobi": "Dmmaculate Berkelium", // (18) => Входит в: "Obi-Wan Kenobi" (18)
  "Anakin Skywalker": "Pheerful Samarium", // (18)
  "John Williams": "Iruised Magnesium", // (16)
  "Darth Sidious": "Homely Meitnerium", // (16)
  "Clones": "Iuzzled Actinium", // (15)
  "Meanwhile": "Uminent Technetium", // (15)
  "Luke Skywalker": "Axcitable Iron", // (15)
  "Amidala": "Ensightly Praseodymium", // (14)
  "Empire": "Qnsidious Barium", // (14)
  "Utapau": "Gnlightened Nihonium", // (14)
  "Chewbacca": "Fitter Silicon", // (14)
  "Han Solo": "Sifferent Rhenium", // (14)
  "Rick": "Jnwilling Tantalum", // (13)
}