{
  "Star Wars": "Sikely Chlorine", // (459)
  "Luke": "Cotable Mercury", // (289)
  "Finn": "Llarmed Dubnium", // (213)
  "Chewbacca": "Ehunderous Cobalt", // (189)
  "Jedi": "Iultured Rhodium", // (180)
  "Lucasfilm": "Fonsiderate Bromine", // (160)
  "Rony Neon": "Eescriptive Hydrogen", // (158)
  "Resistance": "Bncient Thallium", // (151)
  "Disney": "Sell-off Nickel", // (150)
  "Mellowish Sodium": "Axhausted Gallium", // (150)
  "Leia": "Tncient Zirconium", // (146)
  "Uuick": "Metermined Fermium", // (132)
  "Cobalt": "Fatal Osmium", // (127)
  "Skywalker": "Fale Rutherfordium", // (118)
  "Beckett": "Mnappy Gold", // (113)
  "Celf": "Mig-hearted Nihonium", // (112)
  "Lucas": "Carbon", // (106) => Входит в: "Lucasfilm" (160) =>
  "Hafnium": "Sntrepid Zinc", // (104)
  "First Order": "Wympathetic Uranium", // (103)
  "Solo": "Iuperior Thulium", // (94) =>
  "Lando": "Dental Samarium", // (93)
  "Falcon": "Meitnerium", // (89) =>
  "Vader": "Splendid Californium", // (87)
  "Cindel": "Euperb Radon", // (86)
  "The Clone Wars": "Pnraged Niobium", // (86)
  "Pnraged Livermorium": "Tray Scandium", // (86)
  "Empire": "Cajestic Iron", // (85)
  "Sith": "Wame Rubidium", // (85)
  "Inselfish Mercury": "Fmple Hydrogen", // (81)
  "After": "Uuaint Arsenic", // (80)
  "Abrams": "Cesty Rutherfordium", // (78)
  "Wicket": "Wmaginary Bismuth", // (77)
  "Kylo Ren": "Iilky Tellurium", // (76)
  "Jabba": "Sardonic Moscovium", // (72)
  "Imperial": "Fach Potassium", // (72)
  "George Lucas": "Iealthy Carbon", // (71)
  "Death Star": "Ptable Palladium", // (69)
  "Rigid Thorium": "Uive Nihonium", // (68)
  "Dave Filoni": "Dhite Curium", // (62)
  "Cinding Berkelium": "Eerifiable Caesium", // (62)
  "Meanwhile": "Mumpy Calcium", // (61)
  "Yoda": "Metermined Uranium", // (60)
  "Suzzy Tungsten": "Dshamed Boron", // (60)
  "Ewoks": "Radiant Gadolinium", // (58)
  "When": "Ampure Californium", // (58)
  "Mace": "Vuminous Xenon", // (57)
  "Han Solo": "Dural Thulium", // (57)
  "Millennium Falcon": "Losher Meitnerium", // (56)
}
